apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "letsencrypt-issuer.cloudflareSecretName" . }}
  labels:
    {{- include "letsencrypt-issuer.labels" . | nindent 4 }}
stringData:
  api-key: {{ .Values.certManager.cloudflare.apiKey | quote }}
type: Opaque
immutable: false

