{{- if .Values.secret.create }}
{{- $secretData := dict }}
{{- range $k, $v := .Values.secret.data }}
{{- $_ := set $secretData $k $v }}
{{- end }}
{{- if not (hasKey $secretData "devicemap") }}
{{- $_ := set $secretData "devicemap" (printf "%s=%s" .Values.network.id .Values.network.interface) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zerotier.secretName" . }}
  labels:
    {{- include "zerotier.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}

